# Generated by Django 5.0.1 on 2024-01-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlandiasimple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='respitory_rate',
            field=models.CharField(max_length=100),
        ),
    ]
